AllResources = {'Circle.png': './resources/Circle.png',
                'CircleReinforced.png': './resources/CircleReinforced.png',
                'Hit.wav': './resources/Hit.wav', 'icon.pdf': './resources/icon.pdf',
                'Karma_1.png': './resources/Karma_1.png',
                'Karma_10.png': './resources/Karma_10.png',
                'Karma_2.png': './resources/Karma_2.png',
                'Karma_3.png': './resources/Karma_3.png',
                'Karma_4.png': './resources/Karma_4.png',
                'Karma_5.png': './resources/Karma_5.png',
                'Karma_6-1.png': './resources/Karma_6-1.png',
                'Karma_6-2.png': './resources/Karma_6-2.png',
                'Karma_6-3.png': './resources/Karma_6-3.png',
                'Karma_6-4.png': './resources/Karma_6-4.png',
                'Karma_7-1.png': './resources/Karma_7-1.png',
                'Karma_7-2.png': './resources/Karma_7-2.png',
                'Karma_7-3.png': './resources/Karma_7-3.png',
                'Karma_7-4.png': './resources/Karma_7-4.png',
                'Karma_8-2.png': './resources/Karma_8-2.png',
                'Karma_8-3.png': './resources/Karma_8-3.png',
                'Karma_8-4.png': './resources/Karma_8-4.png',
                'Karma_9-3.png': './resources/Karma_9-3.png',
                'Karma_9-4.png': './resources/Karma_9-4.png',
                'Pre.wav': './resources/Pre.wav',
                'tick.wav': './resources/tick.wav',
                'point.png':'./resources/point.png',
                'half_point.png':'./resources/half_point.png',
                'tock.wav': './resources/tock.wav'}

Level = {1:"Karma_1.png",
         2:"Karma_2.png",
         3:"Karma_3.png",
         4:"Karma_4.png",
         5:"Karma_5.png",
         6:"Karma_6-1.png",
         7:"Karma_6-2.png",
         8:"Karma_6-3.png",
         9:"Karma_6-4.png",
         10:"Karma_7-1.png",
         11:"Karma_7-2.png",
         12:"Karma_7-3.png",
         13:"Karma_7-4.png",
         14:"Karma_8-2.png",
         15:"Karma_8-3.png",
         16:"Karma_8-4.png",
         17:"Karma_9-3.png",
         18:"Karma_9-4.png",
         19:"Karma_10.png",
         }
